### ISSUE TITLE
Plot labels dependency

### ISSUE THREAD

**Issue by ewquon** [NREL/windtools#45]
@rthedin, can you add this function directly to plotting.py? 
https://github.com/NREL/windtools/blob/67b4e70c788bce7244fa252296c866c560cc2fa2/windtools/plotting.py#L29-L30

**Comment by rthedin** [comment]
Oof, not sure why I did this or how I mistakenly pushed code like that. Oopsie. Fixed in https://github.com/NREL/windtools/pull/46.
